### ISSUE TITLE
User Name Subdomains

### ISSUE THREAD

**Issue by corbanmailloux** [TheBricksThatHacked/Bucketeer.me#12]
I would like to add support for user name subdomains to access a profile.
For example:
`corban.bucketeer.me` would redirect to my profile.

It seems that the best way to do this would be to add a URL rule to Django to support `/profile/{USERNAME}`, and add an Nginx rewrite rule to push `{USERNAME}.bucketeer.me` to `bucketeer.me/{USERNAME}`. 

On the Nginx-side, I already know the rules necessary. See [here](http://stackoverflow.com/a/21230992).

Thoughts? Do people like this idea? I kind of wanted to move away from the `/profile/{NUMBER}` style anyways.

**Comment by corbanmailloux** [comment]
Additionally, we may have to verify that user names will make valid URLs. We'd have to add some validation on the user names.

**Comment by corbanmailloux** [comment]
I made the URL and view changes on the [profile-by-username branch](https://github.com/TheBricksThatHacked/Bucketeer.me/tree/profile-by-username).

Now we just need to keep users' names from containing `@_+`, on top of Django's built-in rules.

**Comment by corbanmailloux** [comment]
(Mostly a note to self when Nginx gets changed)

`www` won't redirect to a profile, but simply to the main page. Maybe that should be added to the user name validation, or we could simply create a dummy user called `www`. Whatever.

**Comment by Friss** [comment]
Pretty cool idea. I like it

**Comment by corbanmailloux** [comment]
So this is done, minus the Nginx config. 
#Procrastination
Feel free to look over the changes. It just modifies the regex for the user field, and adds a validation to avoid names that would cause collisions.

**Comment by corbanmailloux** [comment]
I did the Nginx config, so I'm merging this into master and updating the server.

**Comment by corbanmailloux** [comment]
Closed via PR #13.

**Comment by corbanmailloux** [comment]
Now live on the server. Check out: http://corban.bucketeer.me

**Comment by corbanmailloux** [comment]
There is a case that I didn't think of. Django usernames are case-sensitive, whereas URLs are not. 
So the user `Mruss3` and `mruss3` can both be valid, but the URL rule will always push to a lower-case version. 

This also means that users with capital letters will never be able to use the subdomain, even if there isn't a collision. 

I propose making it so all user names must be lowercase. Any objections?

**Comment by Friss** [comment]
We could always store usernames as the lowercase version so to the user it doesn't matter. 

On May 17, 2015 9:26:03 PM EDT, Corban Mailloux notifications@github.com wrote:

> There is a case that I didn't think of. Django usernames are
> case-sensitive, whereas URLs are not. 
> So the user `Mruss3` and `mruss3` can both be valid, but the URL rule
> will always push to a lower-case version. 
> 
> This also means that users with capital letters will never be able to
> use the subdomain, even if there isn't a collision. 
> 
> I propose making it so all user names must be lowercase. Any
> objections?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/TheBricksThatHacked/Bucketeer.me/issues/12#issuecomment-102885448

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by corbanmailloux** [comment]
Valid, but then we have to make additional logic for everywhere that a username might be entered. What I had in mind was only allowing lower-case users.
