### ISSUE TITLE
Item CSS classes depend on the item's text

### ISSUE THREAD

**Issue by corbanmailloux** [TheBricksThatHacked/Bucketeer.me#6]
This allows the user's to inject CSS classes, and potentially HTML, into the page.
For an example, create an item with the tag "media"

**Comment by corbanmailloux** [comment]
The issue is on [this line](https://github.com/TheBricksThatHacked/DjangoAPI/blob/c784eddbc364cfb352634baa8e2101a502faea9b/bucket/appbucket/templates/profile.html#L85).

Is there a reason that we need to apply classes based on what the user enters? It seems to open the door for people to apply weird classes and for formatting problems.

**Comment by Friss** [comment]
Well the classes are used for the tag filtering function. It could be changed to be just in a data attribute on the element. There is no real security bug since django doesn't allow raw HTML to be parsed out without a `|safe` flag. Just potential formatting issues.

**Comment by corbanmailloux** [comment]
Good point about the security. I forgot about the `|safe` thing. 
I think we should change it, because I think from a usability sense it will be confusing if a user accidentally enters a tag that matches a bootstrap class name.

**Comment by corbanmailloux** [comment]
@mdw7326 and I were just discussing this issue, and we thought of an alternate solution. 
What if we "namespace" our tag CSS classes? So the class we'd apply and look for would be `bucketeer-media` instead of `media`.

How's that sound?

**Comment by Friss** [comment]
Switching to the data attribute is probably a smarter idea than just applying CSS classes anyway. I just did it that way because jQuery has a function `hasClass()` which makes it easier to implement. 

`data-tags="tag1 tag2 tag3"` and then checking for the substrings when filtering should work just fine.

**Comment by corbanmailloux** [comment]
Awesome. I'm not familiar with the `data-tags` stuff. That's pretty nice.
